brigade:
    name: Friendly Code
    city: Grand Rapids
    meetup-link: "http://www.meetup.com/friendlycode"
    google-group: "https://groups.google.com/forum/?fromgroups#!forum/friendly-code"
    github: "https://github.com/friendlycode"
    mailchimp: "http://eepurl.com/ouJJf"
    facebook: "https://www.facebook.com/friendlycodegr"
    twitter: "https://twitter.com/friendlycodeGR"
    slack: "http://friendlycode.slack.com"
    slack-signup: "http://slackin-friendlycode.herokuapp.com"

content:
    title: Friendly Code | Grand Rapids Code for America Brigade
    meetup-invite: "A casual <a href='http://www.meetup.com/friendlycode'>meetup</a>, on the first and third Tuesday of every month."
    contact: "Allen Clark (<a href=\"mailto:allen@friendlycode.org\">allen@friendlycode.org</a> or <a href=\"http://twitter.com/ItsMeAllenClark\">@ItsMeAllenClark</a>)."
    banner: "./images/gr-skyline.jpg"
    banner-large: "./images/gr-skyline-500-progressive.jpg"
    banner-small: "./images/gr-skyline-300-progressive.jpg"
    projects:
      - name: Viget
        content: "<a href='http://viget.org'>Viget</a>, a Grand Rapids local wiki. To contribute to Viget, check out the <a href=\"http://viget.org/Guide\">Getting Started</a> guide."
      - name: Open Data Portal
        content: The <a href='http://data.grcity.us/'>open data portal</a> for the City of Grand Rapids.
      - name: Parks Millage
        content: A <a href='http://friendlycode.github.io/grparks/'>map of millage dollars</a> drawn on the parks they help fund.
    
      # TODO: enable this after https://github.com/friendlycode/grmade/issues/4
      # - name: GRMade, a directory of Grand Rapids makers
      #   content: "<a href='http://friendlycode.github.io/grmade'>GRMade</a>, a directory of Grand Rapids makers."
    
      - name: Waffle Board
        content: Want to contribute? Check out <a href="https://waffle.io/friendlycode/projects">our Waffle.io board</a> for a list of open issues.

exclude:
- README.md
- Makefile
- Gemfile*
- vendor/
- node_modules

google-analytics:
    use: true
    code: UA-69127535-1
